IBQRAttendance/Controllers/QRCodeController.cs
using IBQRAttendance.Models;
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ZXing;

namespace IBQRAttendance.Controllers
{
    public class QRCodeController : System.Web.Mvc.Controller
    {
        public ActionResult Views()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Register(PassengerInfo passengerInfo)
        {
            var result = PassengerInfo.Register(passengerInfo);
            return Json(result);
        }
        [HttpPost]
        public ActionResult Login(PassengerInfo passengerInfo)
        {
            var result = PassengerInfo.Login(passengerInfo);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult GetDriverInfos()
        {
            var result = DriverInfo.GetDriverInfos();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Booked(Booking booking)
        {
            var result = Booking.Booked(booking);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult CancelBooked(int id)
        {
            var result = Booking.CancelBooked(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult IsBooked(int id)
        {
            var result = Booking.IsBooked(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult ChangePassword(PassengerInfo passengerInfo)
        {
            var result = PassengerInfo.ChangePassword(passengerInfo);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult GetHistories(int id)
        {
            var result = History.GetDriverHistory(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Authenticate(PassengerInfo passengerInfo)
        {
            var result = PassengerInfo.Authenticate(passengerInfo);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
    
}

IBQRAttendance/Views/QRCode/Attendance.cshtml
@model IBQRAttendance.Models.GlobalClass
@{
    ViewBag.Title = "Attendane";

}
<style type="text/css">
    @@media (min-width: 301px ) {
        body {
            background-image: url('/Img/280668513_682904199485150_8543926658523506720_n.jpg');
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center center;
        }

        footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            text-align: center;
        }
    }
</style>


<div class="container" style="background-color: azure; width: 100%;">
    <h2>Attendance</h2>
    <br />
    <div style="width:90%; margin:0 auto;">
        <table id="demoGrid" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>DAYS</th>
                    <th>STAMPS</th>
                    <th>FULLNAME</th>
                    <th>ACTIVITY</th>
                    <th>LEVEL</th>
                    <th>DEPARTMENT</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.LisqRCodeModel)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelitem => item.DAYS)
                        </td>
                        <td>
                            @Html.DisplayFor(modelitem => item.STAMPS)
                        </td>
                        <td>
                            @Html.DisplayFor(modelitem => item.FULLNAME)
                        </td>
                        <td>
                            @Html.DisplayFor(modelitem => item.ACTIVITY)
                        </td>
                        <td>
                            @Html.DisplayFor(modelitem => item.LEVEL)
                        </td>
                        <td>
                            @Html.DisplayFor(modelitem => item.DEPARTMENT)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/DataTables")
@Scripts.Render("~/Scripts/Tables.js")

IBQRAttendance/Views/QRCode/Index.cshtml
@model IBQRAttendance.Models.GlobalClass

@{
    ViewBag.Title = "Generate QR COde";
}
<style type="text/css">
    @@media (min-width: 301px ) {
        body {
            background-image: url('/Img/280668513_682904199485150_8543926658523506720_n.jpg');
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center center;
        }
        footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            text-align: center;
        }
    }
</style>


@using (Html.BeginForm("Register", "QRCode", FormMethod.Post))
{
    <div class="container" style="background-color:azure">
        <h2>Register</h2>
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div id="leftAlign">
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.users.department, new { @class = "control-label col-md-2" })
                    @Html.DropDownListFor(model => model.users.department,
                     EnumHelper.GetSelectList(typeof(IBQRAttendance.Models.Department)), "-- Please Select --",
                     new { @class = "form-control", @id = "department" })
                </div>
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.users.level, new { @class = "control-label col-md-2" })
                    @Html.DropDownListFor(model => model.users.level,
                     EnumHelper.GetSelectList(typeof(IBQRAttendance.Models.Level)), "-- Please Select --",
                     new { @class = "form-control", @id = "level" })
                </div>
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.users.FIRSTNAME, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.users.FIRSTNAME, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.users.FIRSTNAME, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.users.LASTNAME, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.users.LASTNAME, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.users.LASTNAME, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.users.MIDDLENAME, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.users.MIDDLENAME, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.users.MIDDLENAME, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.users.EMAIL, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.users.EMAIL, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.users.EMAIL, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.users.ADDRESS, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.users.ADDRESS, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.users.ADDRESS, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.LabelFor(model => model.users.PHONENUMBER, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.users.PHONENUMBER, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.users.PHONENUMBER, "", new { @class = "text-danger" })
                    </div>
                </div>
                <input type="submit" value="Register" class="btn btn-success" />

            </div>
            <div id="rightAlign">
                <span style="color:red; ">@ViewBag.Message </span>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.qRCodeModel.QRCodeText, new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.qRCodeModel.QRCodeText, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.qRCodeModel.QRCodeText, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.qRCodeModel.QRCodeImagePath, new { @class = "control-label" })
                    @Html.ValidationMessageFor(model => model.qRCodeModel.QRCodeImagePath, "", new { @class = "text-danger" })
                    <div class="col-md-10">
                        @if (Model != null && !String.IsNullOrEmpty(Model.qRCodeModel.QRCodeImagePath))
                        {
                            <img src="@Url.Content(Model.qRCodeModel.QRCodeImagePath)" alt="Image" />
                            @Html.HiddenFor(model => model.qRCodeModel.QRCodeImagePath)
                            @Html.HiddenFor(model => model.qRCodeModel.QRValue)
                        }

                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Generate QR" formaction=@Url.Action("Generate") formmethod="POST" class="btn btn-default" />
                    </div>
                </div>
            </div>

        </div>
        @*<div>
                @Html.ActionLink("Read QR Code", "Read")
            </div>*@
    </div>
}
@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}
<style>
    #rightAlign {
        float: right;
        padding: 20px;
        height: 80%;
        width: 30%;
    }

    #leftAlign {
        float: left;
        padding: 20px;
        width: 70%;
        height: 80%;
    }

    footer {
        padding: 10px;
        text-align: center;
        color: white;
    }
</style>

IBQRAttendance/Views/QRCode/Read.cshtml
@{
    ViewBag.Title = "Home Page";
}
<style type="text/css">
    @@media (min-width: 301px ) {
        body {
            background-image: url('/Img/280668513_682904199485150_8543926658523506720_n.jpg');
            background-repeat: no-repeat;
            background-size: cover;
        }

        footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            text-align: center;
        }

        footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            text-align: center;
        }
    }
</style>
@*<div class="">
        <h1>DFLCMCFI</h1>
        <p class="lead"></p>
        <p><a href="#" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>*@

@*<div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="#">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="#">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="#">Learn more &raquo;</a></p>
        </div>
    </div>*@

IBQRAttendance/Views/QRCode/RegisteredList.cshtml
@model IBQRAttendance.Models.GlobalClass
@{
    ViewBag.Title = "RegisteredList";
}
<style type="text/css">
    @@media (min-width: 301px ) {
        body {
            background-image: url('/Img/280668513_682904199485150_8543926658523506720_n.jpg');
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center center;
        }

        footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            text-align: center;
        }
    }
</style>

@using (Html.BeginForm("RemoveFromList", "QRCode", FormMethod.Post))
{
    <div class="container" style="background-color: azure; width: 100%;">
        <h2>RegisteredList</h2>
        @Html.AntiForgeryToken()
        <br />
        <div style="width:100%; margin:0 auto;">
            <table id="RTable" class="table table-striped table-bordered dt-responsive nowrap" width="100%" height="80%" cellspacing="0">
                <thead>
                    <tr>
                        <th>FIRSTNAME</th>
                        <th>LASTNAME</th>
                        <th>MIDDLENAME</th>
                        <th>EMAIL</th>
                        <th>ADDRESS</th>
                        <th>PHONENUMBER</th>
                        <th>LEVEL</th>
                        <th>DEPARTMENT</th>
                        <th>QR CODE</th>
                        <th>ACTION</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ListUsers)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelitem => item.FIRSTNAME)
                            </td>
                            <td>
                                @Html.DisplayFor(modelitem => item.LASTNAME)
                            </td>
                            <td>
                                @Html.DisplayFor(modelitem => item.MIDDLENAME)
                            </td>
                            <td>
                                @Html.DisplayFor(modelitem => item.EMAIL)
                            </td>
                            <td>
                                @Html.DisplayFor(modelitem => item.ADDRESS)
                            </td>
                            <td>
                                @Html.DisplayFor(modelitem => item.PHONENUMBER)
                            </td>
                            <td>
                                @Html.DisplayFor(modelitem => item._LEVEL)
                            </td>
                            <td>
                                @Html.DisplayFor(modelitem => item._DEPARTMENT)
                            </td>
                            <td>
                                <img src="@Html.DisplayFor(modelitem => item.URLPATH)" id="ImageID" />
                            </td>
                            <td>
                                <input type="submit" value="Remove" formaction=@Url.Action("RemoveFromList", new { USERID = item.USERID }) formmethod="POST" class="btn-danger" />
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/DataTables")
@Scripts.Render("~/Scripts/Tables.js")

IBQRAttendance/Views/QRCode/Views.cshtml
@{
    ViewBag.Title = "Views";
}
<style type="text/css">
    @@media (min-width: 301px ) {
        body {
            background-image: url('/Img/280668513_682904199485150_8543926658523506720_n.jpg');
            background-repeat: no-repeat;
            background-size: cover;
        }

        footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            text-align: center;
        }

        footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            text-align: center;
        }
    }
</style>